# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

exclude: ["README.md"] # files to exclude
disqus:
google_analytics:

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: vivekragunathan.github.io

description: Yay! Live on GitHub pages ....
author:
  name: Vivek Ragunathan
  email: email@vivekragunathan.com
  github: vivekragunathan
  twitter: vivekragunathan
  pinterest:
  linkedin: vivekragunathan
  bio: Yay! Live on GitHub pages ....
  email_md5: 747cacf97e1f178ab5b16f1d853ef230
  #726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:

include:       ['_pages','_images']
markdown:      redcarpet
highlighter:   pygments
redcarpet:
  extensions:  ['footnotes', 'smart', 'tables', 'with_toc_data']
gems:          [jekyll-paginate]
permalink:     pretty
paginate:      5
# pagination based on number of posts
paginate_path: "page:num"

sass:
  compressed: true
