title: A Developer's Experience
theme: soho
publishDir: docs/
baseURL: ''
languageCode: en
enableInlineShortcodes: true
summarylength: 10
enableEmoji: true
params:
  author: HigherKindedType
  description: >-
    The romantic image of an über-programmer is someone who fires up Emacs,
    types like a machine gun, and delivers a flawless final product from
    scratch. A more accurate image would be someone who stares quietly into
    space for a few minutes and then says Hmm. I think I’ve seen something like
    this before – John D. Cook
  about: >-
    The romantic image of an über-programmer is someone who fires up Emacs,
    types like a machine gun, and delivers a flawless final product from
    scratch. A more accurate image would be someone who stares quietly into
    space for a few minutes and then says Hmm. I think I’ve seen something like
    this before – John D. Cook
  profilePicture: images/profile.png
  avatar: /images/profile.png
  github: vivekragunathan
  themeColor: '#347B98'
  customCss:
    - css/blockquote.css
    - css/custom.css
  socialIcons:
    - icon: fa-stack-overflow
      title: Stackoverflow
      url: 'https://stackoverflow.com/users/495612'
    - icon: fa-github
      title: GitHub
      url: 'https://github.com/vivekragunathan'
    - icon: fa-twitter
      title: Twitter
      url: 'https://twitter.com/higherkindedtpe'
menu:
  main:
    - name: Posts
      weight: 100
      identifier: posts
      url: /post/
    - name: Pages
      weight: 200
      identifier: pages
      url: /pages
    - name: Qs
      weight: 300
      identifier: quotes
      url: /quotations
    - name: About
      identifier: about
      weight: 300
      url: /about/
markup:
  goldmark:
    parser:
      attribute:
        block: true
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ''
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    style: zenburn
    tabWidth: 2
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
taxonomies:
  category: categories
  series: series
  tag: tags
# Unfilled fields
  copyright: ''
  twitter: example
  misskey: user profile url
  mastodon: user profile url
  email: example@domain.com
  utterances: example/example.github.io
  url: 'https://example.com'
  keywords: 'blog, google analytics'